name: audioplayers_example
description: Demonstrates how to use the audioplayers plugin.

dependencies:
  flutter:
    sdk: flutter
  audioplayers:
    path: ../
  http: 
  path_provider: 
  path_provider_macos:
  provider: 

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

  assets:
    - assets/audio.mp3
    - assets/audio2.mp3
    - assets/messenger.mp3

environment:
  sdk: ">=2.12.0-0 <3.0.0"
